name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🐙 Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.MY_TOKEN }}
          base: header, activity
          user: "chernyshov-dev"
          config_timezone: Europe/Moscow
          plugin_languages_ignored: html, css
          plugin_languages: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: yes
      - name: 🏆 Achievements
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.MY_TOKEN }}
          user: "chernyshov-dev"
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_lines: yes
